name: CD

on:
  push:
    branches:
    - main
    - support/*
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - '.editorconfig'
    - '.gitattributes'
    - '.gitignore'
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/pull_request_template.md'

defaults: *default-defaults

jobs:
  build:
    name: 'Continuous delivery'
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
    - *checkout
    - *setup-dotnet
    - *setup-nuget
    - *restore
    - *build
    - *test
    - *pack
    - *build-css-package
    - *upload-artifacts
