name: Release

on:
  release:
    types:
      - published

defaults: *default-defaults

jobs:
  build:
    name: 'Deploy release'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - *checkout
    - *setup-dotnet
    - *setup-nuget
    - name: Setup Verlite
      run: |
        verlite_version="$(grep '"Verlite\.MsBuild"' Directory.Build.props | LC_ALL=en_US.utf8 grep -Po 'Version="\K[^"]+')"
        dotnet tool install --global Verlite.CLI --version "$verlite_version"
        verlite . --enable-shadow-repo --auto-fetch --verbosity verbatim
    - name: Verify tag
      run: |
        [[ "v$(verlite .)" == "${GITHUB_REF#refs/*/}" ]] # error out if the versions don't match
    - *restore
    - *build
    - *test
    - *pack
    - *build-css-package
    - *upload-artifacts
    - name: 'Upload release'
      run: |
        set -x
        tag="${GITHUB_REF#refs/*/}"
        files=()

        IFS=$'\n';
        for asset in $(find ./artifacts -maxdepth 1 -name "*.zip"); do
          files+=("$asset")
        done

        IFS=$'\n';
        for asset in $(find ./artifacts -name "*.nupkg"); do
          files+=("$asset")
        done

        gh release upload "$tag" "${files[@]}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
